# Generated by Django 4.0.3 on 2022-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtvp',
            name='field_value_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
