# Generated by Django 4.0.3 on 2022-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanleverinfo_filters',
            name='filter_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
