# Generated by Django 4.0.3 on 2022-04-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gld_addition_log',
            table='aanlevering"."gld_addition_log',
        ),
    ]
