# Generated by Django 4.0.3 on 2022-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0002_alter_gld_addition_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gld_addition_log',
            name='addition_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
