# Generated by Django 4.0.3 on 2022-03-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0002_aanleverinfo_filters_filter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aanleverinfo_filters',
            name='filter_id',
        ),
    ]
