# Generated by Django 4.0.3 on 2022-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0002_measurementtvp_field_value_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementtimeseries',
            name='filter_nr',
        ),
        migrations.RemoveField(
            model_name='measurementtimeseries',
            name='gmw_bro_id',
        ),
        migrations.AddField(
            model_name='measurementtimeseries',
            name='observation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='groundwater_level_dossier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='result_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
