# Generated by Django 4.0.3 on 2022-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0003_remove_aanleverinfo_filters_filter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gld_registration_log',
            old_name='location',
            new_name='filter_id',
        ),
        migrations.AddField(
            model_name='gld_registration_log',
            name='gwm_bro_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
