# Generated by Django 4.0.3 on 2022-04-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0003_gld_addition_log_addition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gld_addition_log',
            name='addition_type',
        ),
    ]
