# Generated by Django 4.0.3 on 2022-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0004_rename_location_gld_registration_log_filter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gld_registration_log',
            name='gld_bro_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
