# Generated by Django 4.0.3 on 2022-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0004_rename_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMeasurementInstrumentType',
            new_name='TypeMeasementInstrumentType',
        ),
    ]
