# Generated by Django 4.0.3 on 2022-04-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0004_remove_gld_addition_log_addition_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveredlocations',
            table='gmw"."delivered_locations',
        ),
        migrations.AlterModelTable(
            name='deliveredverticalpositions',
            table='gmw"."delivered_vertical_positions',
        ),
        migrations.AlterModelTable(
            name='gld_registration_log',
            table='aanlevering"."gld_registration_log',
        ),
        migrations.AlterModelTable(
            name='groundwaterleveldossier',
            table='gld"."groundwater_level_dossier',
        ),
        migrations.AlterModelTable(
            name='groundwatermonitoringtubes',
            table='gmw"."groundwater_monitoring_tubes',
        ),
        migrations.AlterModelTable(
            name='groundwatermonitoringwells',
            table='gmw"."groundwater_monitoring_wells',
        ),
        migrations.AlterModelTable(
            name='measurementpointmetadata',
            table='gld"."measurement_point_metadata',
        ),
        migrations.AlterModelTable(
            name='measurementtimeseries',
            table='gld"."measurement_time_series',
        ),
        migrations.AlterModelTable(
            name='measurementtimeseriestvpobservation',
            table='gld"."measurement_timeseries_tvp_observation',
        ),
        migrations.AlterModelTable(
            name='measurementtvp',
            table='gld"."measurement_tvp',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='gld"."observation',
        ),
        migrations.AlterModelTable(
            name='observationmetadata',
            table='gld"."observation_metadata',
        ),
        migrations.AlterModelTable(
            name='observationprocess',
            table='gld"."observation_process',
        ),
        migrations.AlterModelTable(
            name='responsibleparty',
            table='gld"."responsible_party',
        ),
        migrations.AlterModelTable(
            name='typeairpressurecompensation',
            table='gld"."type_air_pressure_compensation',
        ),
        migrations.AlterModelTable(
            name='typecensoredreasoncode',
            table='gld"."type_censored_reason_code',
        ),
        migrations.AlterModelTable(
            name='typeevaluationprocedure',
            table='gld"."type_evaluation_procedure',
        ),
        migrations.AlterModelTable(
            name='typeinterpolationcode',
            table='gld"."type_interpolation_code',
        ),
        migrations.AlterModelTable(
            name='typemeasurementinstrumenttype',
            table='gld"."type_measurement_instrument_type',
        ),
        migrations.AlterModelTable(
            name='typeobservationtype',
            table='gld"."type_observation_type',
        ),
        migrations.AlterModelTable(
            name='typeprocessreference',
            table='gld"."type_process_reference',
        ),
        migrations.AlterModelTable(
            name='typeprocesstype',
            table='gld"."type_process_type',
        ),
        migrations.AlterModelTable(
            name='typestatuscode',
            table='gld"."type_status_code',
        ),
        migrations.AlterModelTable(
            name='typestatusqualitycontrol',
            table='gld"."type_status_quality_control',
        ),
    ]
