# Generated by Django 4.0.3 on 2022-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0005_alter_deliveredlocations_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemeasurementinstrumenttype',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
