# Generated by Django 4.0.3 on 2022-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0005_gld_registration_log_gld_bro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gld_addition_log_controle',
            name='last_changed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
