# Generated by Django 4.0.3 on 2022-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0005_rename_typemeasurementinstrumenttype_typemeasementinstrumenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmetadata',
            name='date_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
