# Generated by Django 4.0.3 on 2022-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0006_gld_addition_log_controle_last_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gld_addition_log_controle',
            name='last_changed',
        ),
        migrations.AddField(
            model_name='gld_registration_log',
            name='last_changed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
