# Generated by Django 4.0.3 on 2022-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0006_alter_observationmetadata_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmetadata',
            name='date_stamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
