# Generated by Django 4.0.3 on 2022-04-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0006_typemeasurementinstrumenttype_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemeasurementinstrumenttype',
            name='test',
        ),
    ]
