# Generated by Django 4.0.3 on 2022-04-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0007_alter_observationmetadata_date_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='procedure_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
