# Generated by Django 4.0.3 on 2022-04-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0007_remove_typemeasurementinstrumenttype_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementTimeseriesTvpObservation',
        ),
        migrations.AlterModelOptions(
            name='groundwaterleveldossier',
            options={'managed': True, 'verbose_name': 'Groundwaterlevel dossier', 'verbose_name_plural': 'Groundwaterlevel dossier'},
        ),
    ]
