# Generated by Django 4.0.3 on 2022-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0008_delete_measurementtimeseriestvpobservation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveredlocations',
            options={'managed': True, 'verbose_name_plural': 'Delivered locations'},
        ),
        migrations.AlterModelOptions(
            name='deliveredverticalpositions',
            options={'managed': True, 'verbose_name_plural': 'Delivered vertical positions'},
        ),
        migrations.AlterModelOptions(
            name='gld_addition_log',
            options={'verbose_name': 'GLD addition logging', 'verbose_name_plural': 'GLD addition logging'},
        ),
        migrations.AlterModelOptions(
            name='gld_registration_log',
            options={'verbose_name': 'GLD registration logging', 'verbose_name_plural': 'GLD registration logging'},
        ),
        migrations.AlterModelOptions(
            name='groundwatermonitoringtubes',
            options={'managed': True, 'verbose_name_plural': 'Groundwater monitoring tubes'},
        ),
        migrations.AlterModelOptions(
            name='groundwatermonitoringwells',
            options={'managed': True, 'verbose_name_plural': 'Groundwater monitoring wells'},
        ),
        migrations.AlterModelOptions(
            name='measurementtvp',
            options={'managed': True, 'verbose_name': 'Measurement time-value pairs', 'verbose_name_plural': 'Measurement time-value pairs'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': True, 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='typeairpressurecompensation',
            options={'managed': True, 'verbose_name_plural': 'Air pressure compensation'},
        ),
        migrations.AlterModelOptions(
            name='typecensoredreasoncode',
            options={'managed': True, 'verbose_name_plural': 'Censor reasons'},
        ),
        migrations.AlterModelOptions(
            name='typeevaluationprocedure',
            options={'managed': True, 'verbose_name_plural': 'Evaluation procedures'},
        ),
        migrations.AlterModelOptions(
            name='typeinterpolationcode',
            options={'managed': True, 'verbose_name_plural': 'Interpolation codes'},
        ),
        migrations.AlterModelOptions(
            name='typemeasurementinstrumenttype',
            options={'managed': True, 'verbose_name_plural': 'Measurement instrument types'},
        ),
        migrations.AlterModelOptions(
            name='typeobservationtype',
            options={'managed': True, 'verbose_name_plural': 'Observation types'},
        ),
        migrations.AlterModelOptions(
            name='typeprocessreference',
            options={'managed': True, 'verbose_name_plural': 'Process references'},
        ),
        migrations.AlterModelOptions(
            name='typeprocesstype',
            options={'managed': True, 'verbose_name_plural': 'Process types'},
        ),
        migrations.AlterModelOptions(
            name='typestatuscode',
            options={'managed': True, 'verbose_name_plural': 'Status codes'},
        ),
        migrations.AlterModelOptions(
            name='typestatusqualitycontrol',
            options={'managed': True, 'verbose_name_plural': 'Quality control types'},
        ),
        migrations.AddField(
            model_name='gld_addition_log',
            name='addition_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
