# Generated by Django 4.0.3 on 2022-04-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0008_observation_procedure_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gld_addition_log_controle',
            old_name='location',
            new_name='observation_id',
        ),
        migrations.RenameField(
            model_name='gld_addition_log_volledig',
            old_name='location',
            new_name='observation_id',
        ),
        migrations.RenameField(
            model_name='gld_addition_log_voorlopig',
            old_name='location',
            new_name='observation_id',
        ),
    ]
