# Generated by Django 4.0.3 on 2022-03-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0009_alter_measurementtimeseries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementtimeseries',
            options={'managed': True, 'verbose_name': 'Measurement timeseries', 'verbose_name_plural': 'Measurement timeseries'},
        ),
    ]
