# Generated by Django 4.0.3 on 2022-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0009_rename_location_gld_addition_log_controle_observation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gld_addition_log_voorlopig',
            name='file',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
