# Generated by Django 4.0.3 on 2022-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0010_alter_measurementtimeseries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtimeseries',
            name='filter_nr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurementtimeseries',
            name='gmw_bro_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
