# Generated by Django 4.0.3 on 2022-04-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0010_gld_addition_log_voorlopig_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='procedure_uuid',
            new_name='status',
        ),
    ]
