# Generated by Django 4.0.3 on 2022-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0010_alter_gld_addition_log_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gld_addition_log',
            name='comments',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
