# Generated by Django 4.0.3 on 2022-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0011_alter_gld_addition_log_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gld_registration_log',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubes',
            name='groundwater_monitoring_tube_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
