# Generated by Django 4.0.3 on 2022-03-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0011_measurementtimeseries_filter_nr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementtvp',
            options={'managed': True, 'verbose_name': 'Measurement tvp', 'verbose_name_plural': 'Measurement tvp'},
        ),
    ]
