# Generated by Django 4.0.3 on 2022-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0011_rename_procedure_uuid_observation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gld_addition_log_voorlopig',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
