# Generated by Django 4.0.3 on 2022-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0012_alter_gld_registration_log_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gld_registration_log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
