# Generated by Django 4.0.3 on 2022-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0012_alter_measurementtvp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtvp',
            name='measurement_metadata_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
