# Generated by Django 4.0.3 on 2022-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0012_alter_gld_addition_log_voorlopig_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='gld_registration_log',
            name='corrections_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gld_registration_log',
            name='file',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gld_registration_log',
            name='quality_regime',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gld_registration_log',
            name='timestamp_end_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
