# Generated by Django 4.0.3 on 2022-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0013_alter_gld_registration_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwatermonitoringtubes',
            name='deliver_to_bro',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
