# Generated by Django 4.0.3 on 2022-03-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0013_measurementtvp_measurement_metadata_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundwaterleveldossier',
            options={'managed': True, 'verbose_name': 'Groundwaterlevel dossier', 'verbose_name_plural': 'Groundwater level dossier'},
        ),
    ]
