# Generated by Django 4.0.3 on 2022-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0014_alter_groundwaterleveldossier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterleveldossier',
            name='gmw_bro_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groundwaterleveldossier',
            name='tube_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
