# Generated by Django 4.0.3 on 2022-03-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0015_groundwaterleveldossier_gmw_bro_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundwaterleveldossier',
            name='tube_number',
        ),
    ]
