# Generated by Django 4.0.3 on 2022-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0016_remove_groundwaterleveldossier_tube_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterleveldossier',
            name='gld_bro_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
