# Generated by Django 4.0.3 on 2023-10-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0003_measuringpoint_groundwater_monitoring_tube'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmw_registration_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('gwm_bro_id', models.CharField(blank=True, max_length=254, null=True)),
                ('filter_id', models.CharField(blank=True, max_length=254, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_id', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_status', models.CharField(blank=True, max_length=254, null=True)),
                ('gld_bro_id', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('last_changed', models.DateField(blank=True, null=True)),
                ('corrections_applied', models.BooleanField(blank=True, null=True)),
                ('timestamp_end_registration', models.DateTimeField(blank=True, null=True)),
                ('quality_regime', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.CharField(blank=True, max_length=254, null=True)),
                ('process_status', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'GMN registration logging',
                'verbose_name_plural': 'GMN registration logging',
                'db_table': 'gmn"."gmn_registration_log',
            },
        ),
        migrations.AlterField(
            model_name='measuringpoint',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Meetpunt naam'),
        ),
    ]
