# Generated by Django 4.0.3 on 2023-10-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0004_gmw_registration_log_alter_measuringpoint_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmw_registration_log',
            old_name='gld_bro_id',
            new_name='gmn_bro_id',
        ),
        migrations.RemoveField(
            model_name='gmw_registration_log',
            name='filter_id',
        ),
        migrations.RemoveField(
            model_name='gmw_registration_log',
            name='gwm_bro_id',
        ),
    ]
