# Generated by Django 4.0.3 on 2023-10-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0005_rename_gld_bro_id_gmw_registration_log_gmn_bro_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gmw_registration_log',
            new_name='gmn_registration_log',
        ),
    ]
