# Generated by Django 4.0.3 on 2023-10-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0007_gmn_registration_log_object_id_accountable_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundwatermonitoringnet',
            old_name='broid_gmn',
            new_name='gmn_bro_id',
        ),
    ]
