# Generated by Django 4.0.3 on 2023-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0008_rename_broid_gmn_groundwatermonitoringnet_gmn_bro_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmn_registration_log',
            options={'verbose_name': 'GMN Registration Log', 'verbose_name_plural': 'GMN Registration Logs'},
        ),
        migrations.AddField(
            model_name='groundwatermonitoringnet',
            name='deliver_to_bro',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
