# Generated by Django 4.0.3 on 2023-10-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0010_alter_gmn_registration_log_levering_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmn_registration_log',
            name='levering_status_info',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gmn_registration_log',
            name='levering_status',
            field=models.CharField(blank=True, choices=[('0', 'Nog niet aangeleverd'), ('1', '1 keer gefaald'), ('2', '2 keer gefaald'), ('3', '3 keer gefaald'), ('4', 'Succesvol aangeleverd')], default=0, max_length=10, null=True),
        ),
    ]
