# Generated by Django 4.0.3 on 2023-10-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0012_alter_gmn_registration_log_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringpoint',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meetpunt naam'),
        ),
    ]
