# Generated by Django 4.0.3 on 2023-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0013_alter_measuringpoint_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediateevent',
            name='event_name',
        ),
        migrations.AddField(
            model_name='intermediateevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoints'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoints'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='intermediateevent',
            name='measuring_points',
            field=models.ManyToManyField(blank=True, to='gmn_aanlevering.measuringpoint'),
        ),
        migrations.AddField(
            model_name='intermediateevent',
            name='synced_to_bro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
