# Generated by Django 4.0.3 on 2023-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0003_remove_groundwatermonitoringtubesstatic_gmn_measuring_point'),
        ('gmn_aanlevering', '0014_remove_intermediateevent_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='deliver_to_bro',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='delivery_accountable_party',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='delivery_responsible_party',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='groundwater_aspect',
            field=models.CharField(choices=[('kwaliteit', 'kwaliteit'), ('kwantiteit', 'kwantiteit')], max_length=235, verbose_name='Grondwateraspect'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='object_id_accountable_party',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='quality_regime',
            field=models.CharField(choices=[('IMBRO', 'IMBRO'), ('IMBRO/A', 'IMBRO/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='start_date_monitoring',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='event_type',
            field=models.CharField(choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoints'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoints'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='synced_to_bro',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='measuringpoint',
            name='groundwater_monitoring_tube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringtubesstatic'),
        ),
    ]
