# Generated by Django 4.0.3 on 2023-10-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0015_alter_groundwatermonitoringnet_deliver_to_bro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediateevent',
            name='measuring_points',
        ),
        migrations.AddField(
            model_name='intermediateevent',
            name='measuring_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmn_aanlevering.measuringpoint'),
        ),
        migrations.AddField(
            model_name='measuringpoint',
            name='removed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='event_type',
            field=models.CharField(choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoint'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoints'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True),
        ),
    ]
