# Generated by Django 4.0.3 on 2023-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0016_remove_intermediateevent_measuring_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringpoint',
            name='added_to_gmn_date',
            field=models.DateField(null=True),
        ),
    ]
