# Generated by Django 4.0.3 on 2023-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0017_measuringpoint_added_to_gmn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuringpoint',
            name='removed',
        ),
        migrations.AddField(
            model_name='measuringpoint',
            name='deleted_from_gmn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
