# Generated by Django 4.0.3 on 2023-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0018_remove_measuringpoint_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediateevent',
            name='gmn',
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringnet',
            name='end_date_monitoring',
            field=models.DateField(blank=True, help_text='Als een Meetnet verwijderd moet worden uit de BRO, verwijder het dan NIET uit de BRO-Connector. Vul dit veld in om de verwijdering uit de BRO te realiseren.', null=True),
        ),
        migrations.AlterField(
            model_name='measuringpoint',
            name='deleted_from_gmn_date',
            field=models.DateField(blank=True, help_text='Als een Meetpunt van een meetnet verwijderd moet worden, verwijder het object dan NIET uit de BRO-Connector, maar vul dit veld in!', null=True),
        ),
    ]
