# Generated by Django 4.0.3 on 2023-10-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0019_remove_intermediateevent_gmn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediateevent',
            name='gmn',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='gmn_aanlevering.groundwatermonitoringnet'),
            preserve_default=False,
        ),
    ]
