# Generated by Django 4.0.3 on 2023-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0020_intermediateevent_gmn'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediateevent',
            name='deliver_to_bro',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
