# Generated by Django 4.0.3 on 2023-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0021_intermediateevent_deliver_to_bro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringpoint',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Meetpunt naam'),
        ),
    ]
