# Generated by Django 4.0.3 on 2023-10-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0022_alter_measuringpoint_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmn_bro_sync_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoint'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoints'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True)),
                ('gmn_bro_id', models.CharField(blank=True, max_length=254, null=True)),
                ('object_id_accountable_party', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_id', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_status', models.CharField(blank=True, choices=[('0', 'Nog niet aangeleverd'), ('1', '1 keer gefaald'), ('2', '2 keer gefaald'), ('3', '3 keer gefaald'), ('4', 'Succesvol aangeleverd')], default=0, max_length=10, null=True)),
                ('levering_status_info', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('last_changed', models.CharField(blank=True, max_length=254, null=True)),
                ('corrections_applied', models.BooleanField(blank=True, null=True)),
                ('timestamp_end_registration', models.DateTimeField(blank=True, null=True)),
                ('quality_regime', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.CharField(blank=True, max_length=254, null=True)),
                ('process_status', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'GMN Registration Log',
                'verbose_name_plural': 'GMN Registration Logs',
                'db_table': 'gmn"."gmn_bro_sync_log',
            },
        ),
        migrations.DeleteModel(
            name='gmn_registration_log',
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='measuring_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmn_aanlevering.measuringpoint'),
        ),
    ]
