# Generated by Django 4.0.3 on 2023-11-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0023_gmn_bro_sync_log_delete_gmn_registration_log_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmn_bro_sync_log',
            options={'verbose_name': 'GMN Bro Sync Log', 'verbose_name_plural': 'GMN Bro Sync Logs'},
        ),
        migrations.AddField(
            model_name='gmn_bro_sync_log',
            name='measuringpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmn_aanlevering.measuringpoint'),
        ),
        migrations.AddField(
            model_name='measuringpoint',
            name='synced_to_bro',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
