# Generated by Django 4.0.3 on 2023-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0024_alter_gmn_bro_sync_log_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringpoint',
            name='removed_from_BRO_gmn',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gmn_bro_sync_log',
            name='event_type',
            field=models.CharField(choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoint'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoint'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intermediateevent',
            name='event_type',
            field=models.CharField(choices=[('GMN_StartRegistration', 'Start Registration'), ('GMN_MeasuringPoint', 'Add MeasuringPoint'), ('GMN_MeasuringPointEndDate', 'Remove MeasuringPoint'), ('GMN_Closure', 'GMN Closure')], max_length=25, null=True),
        ),
    ]
