# Generated by Django 4.0.3 on 2023-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmn_aanlevering', '0025_measuringpoint_removed_from_bro_gmn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwatermonitoringnet',
            name='removed_from_BRO',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='measuringpoint',
            name='removed_from_BRO_gmn',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
