[envs.default]
path = ".bro_connector"
dependencies = [
    "asgiref",
    "certifi",
    "charset-normalizer",
    "Django==4.0.3",
    "django-extensions",
    "django-admin-generator==2.2.1",
    "django-jazzmin==2.6.0",
    "django-modeladmin-reorder==0.3.1",
    "django-utils2==2.12.1",
    "idna",
    "lxml",
    "numpy",
    "pandas==2.1.3",
    "psycopg2-binary",
    "python-dateutil",
    "python-utils",
    "pytz",
    "six",
    "sqlparse",
    "tzdata",
    "urllib3",
    "uuid",
    "xmltodict",
    "bro-exchange @ git+https://github.com/nens/bro-exchange",
    "django-reversion-compare",
    # gwdatalens:
    "pyproj",
    "matplotlib",
    "pandas",
    "sqlalchemy",
    "geopandas",
    "django_plotly_dash",
    "dpd-static-support",
    "django-bootstrap4",
    "dash",
    "dash-bootstrap-components",
    "flask-caching",
    "waitress",
    "tqdm",
    "traval",
    "pastas",
    "pastastore",
    "hydropandas",
    "icecream",
    "i18nice[YAML]",
    "tomli",
]
