[build-system]
requires = ["setuptools>=70.1"]

[project]
name = "bro-connector"
requires-python = "==3.12.*"
version = "0.1.1.dev0"
description = "Complete groundwatermonitoring data management for BRO"
readme = "README.md"
license = { file = "LICENSE.MD" }
authors = []

dependencies = [
    "bro_exchange @ git+https://github.com/nens/bro-exchange@7948005c9f15a9ca383a7c50d44b10b93dba57be",
    "channels>=4.0.0",
    "cryptography>=44.0.0",
    "dash==2.18.2",
    "dash-bootstrap-components==1.7.1",
    "dash-core-components==2.0.0",
    "dash-html-components==2.0.0",
    "dash-table==5.0.0",
    "Django>=5.2",
    "django-admin-autocomplete-filter==0.7.1",
    "django-admin-generator==2.2.1",
    "django-bootstrap4",
    "django-extensions==3.2.3",
    "django-jazzmin>=3.0.0",
    "django-modeladmin-reorder==0.3.1",
    "django-plotly-dash",
    "django-reversion==5.0.12",
    "django-reversion-compare==0.17.0",
    "django-static-jquery==2.1.4",
    "django-utils2==2.12.1",
    "djangorestframework==3.15.1",
    "dpd-components==0.1.0",
    "dpd-static-support==0.0.5",
    "factory-boy>=3.3.3",
    "Flask==3.0.3",
    "Flask-Caching",
    "geopandas",
    "gunicorn>=23.0.0",
    "hydropandas>=0.17.1",
    "i18nice[YAML]",
    "Jinja2>=3.1.4",
    "lxml",
    "numpy>=2.2",
    "packaging==24.0",
    "pandas>=3.0",
    "pastas>=1.6.0",
    "pastastore>=1.11.0",
    "cachetools==6.2.4",
    "plotly==6.0.1",
    "polars",
    "psycopg2-binary",
    "pyOpenSSL",
    "pyproj>=3.7.0",
    "pysftp==0.2.9",
    "python-dotenv>=1.1.0",
    "python-utils==3.8.2",
    "pytz",
    "requests",
    "rich==13.7.1",
    "six==1.16.0",
    "sqlparse==0.5.1",
    "SQLAlchemy",
    "toml==0.10.2",
    "traval",
    "tzdata==2024.1",
    "urllib3>=2.2.2",
    "Werkzeug>=3.0.4",
    "django-image-uploader-widget",
    "pytest>=8.4.0",
    "pre-commit>=4.5.1",
    "psycopg2>=2.9.12",
    "pytest-django>=4.12.0",
    "xmltodict>=1.0.4",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = [
    "bro_connector"
]

[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["tests"]
log_level = "DEBUG"
DJANGO_SETTINGS_MODULE = "main.settings.development"

[tool.coverage.run]
source = [
    "bro", "frd", "gar", "gld", "gmn", "gmw", "tools", "main"
]

[tool.coverage.report]
show_missing = true
skip_empty = true

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP", "C"]
ignore = ["C901", "UP008"]

[tool.zest-releaser]
release = false
