"""
Django settings for provincie_zeeland_gld project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

import django.db.models.options as options
options.DEFAULT_NAMES = options.DEFAULT_NAMES + ('schema',)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1b2-79o0!+@%9d6gt@7k5-8=8(r@&x-(15!o7+zo-zgwg4)gbv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gld_aanlevering',
    'django_admin_generator',
    'admin_reorder']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'admin_reorder.middleware.ModelAdminReorder',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'provincie_zeeland_gld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'provincie_zeeland_gld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#DATABASE_ROUTERS = ['database_routers.zeeland_gld.PostgresRouter']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gld_zeeland_productie',                      
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5433',
        'OPTIONS':{'options': '-c search_path=django_admin'}
}}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ADMIN_REORDER = (
    # First group
    {'app': 'gld_aanlevering', 'label': 'GLD Registratie',
      'models': ('gld_aanlevering.gld_registration_log',
                 'gld_aanlevering.gld_addition_log')
    },
    # Second group: same app, but different label
    {'app': 'gld_aanlevering', 'label': 'Provincie Zeeland GLD - Data',
      'models': ('gld_aanlevering.Observation',
                 'gld_aanlevering.GroundwaterLevelDossier',
                'gld_aanlevering.MeasurementPointMetadata',
                'gld_aanlevering.MeasurementTimeSeries',
                'gld_aanlevering.MeasurementTimeseriesTvpObservation',
                'gld_aanlevering.MeasurementTvp',
                'gld_aanlevering.ObservationMetadata',
                'gld_aanlevering.ObservationProcess',
                'gld_aanlevering.ResponsibleParty')
    },
    {'app': 'gld_aanlevering', 'label': 'Provincie Zeeland GLD - Types',
      'models': ('gld_aanlevering.TypeAirPressureCompensation',
                'gld_aanlevering.TypeCensoredReasonCode',
                'gld_aanlevering.TypeEvaluationProcedure',
                'gld_aanlevering.TypeInterpolationCode',
                'gld_aanlevering.TypeMeasurementInstrumentType',
                'gld_aanlevering.TypeObservationType',
                'gld_aanlevering.TypeProcessReference',
                'gld_aanlevering.TypeProcessType',
                'gld_aanlevering.TypeStatusCode',
                'gld_aanlevering.TypeStatusQualityControl')
    },
    {'app': 'gld_aanlevering', 'label': 'Provincie Zeeland GWM - Data',
      'models': ('gld_aanlevering.GroundwaterMonitoringWells',
                 'gld_aanlevering.GroundwaterMonitoringTubes',
                 'gld_aanlevering.DeliveredLocations',
                 'gld_aanlevering.DeliveredVerticalPositions')
    },
)


# # BROCONVERTER SETTINGS
GLD_AANLEVERING_SETTINGS = {
    'acces_token_bro_portal_demo': {
        'user':'2f382895e91a|27376655|630',
        'pass':'84d0049b0bb9eb0924fa88f4472e3222eed1c56b0111c9b927c81d2c77df67c9'
    },
    'acces_token_bro_portal_provincie_zeeland': {
        'user':'',
        'pass':''
    },
    'monitoringnetworks':None,
    'demo':True,
    'additions_dir':os.path.join(BASE_DIR, 'gld_aanlevering/additions'),
    'startregistrations_dir':os.path.join(BASE_DIR, 'gld_aanlevering/startregistrations'),
}

# Quick Scan SETTINGS
QUICK_SCAN_SETTINGS = {
 'max_groundwater_level':10,
 'max_change_two_measurements':1,
 'liveliness_maximum_flatline_duration':100
}
