"""
Django settings for provincie_zeeland_gld project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

import django.db.models.options as options
options.DEFAULT_NAMES = options.DEFAULT_NAMES + ('schema',)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1b2-79o0!+@%9d6gt@7k5-8=8(r@&x-(15!o7+zo-zgwg4)gbv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gld_aanlevering',
    'django_admin_generator']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'provincie_zeeland_gld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'provincie_zeeland_gld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gld_zeeland_productie',                      
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5433',
        'OPTIONS':{'options': '-c search_path=public'}
    }
}

#DATABASE_ROUTERS = ['database_routers.zeeland_gld.PostgresRouter']

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ADMIN_REORDER = (
#     # First group
#     {'app': '_nens_demo', 'label': 'GLD Registratie',
#      'models': ('_nens_demo.aanleverinfo_filters',
#                 '_nens_demo.gld_registration_log',
#                 '_nens_demo.gld_addition_log_controle',
#                 '_nens_demo.gld_addition_log_voorlopig',
#                 '_nens_demo.gld_addition_log_volledig')
#     },
#     # Second group: same app, but different label
#     {'app': 'zeeland_gld', 'label': 'Provincie Zeeland GLD - Data',
#      'models': ('zeeland_gld.GroundwaterLevelDossier',
#                 'zeeland_gld.MeasurementPointMetadata',
#                 'zeeland_gld.MeasurementTimeSeries',
#                 'zeeland_gld.MeasurementTimeseriesTvpObservation',
#                 'zeeland_gld.MeasurementTvp',
#                 'zeeland_gld.ObservationMetadata',
#                 'zeeland_gld.ObservationProcess',
#                 'zeeland_gld.ResponsibleParty')
#     },
#     {'app': 'zeeland_gld', 'label': 'Provincie Zeeland GLD - Types',
#      'models': ('zeeland_gld.TypeAirPressureCompensation',
#                 'zeeland_gld.TypeCensoredReasonCode',
#                 'zeeland_gld.TypeEvaluationProcedure',
#                 'zeeland_gld.TypeInterpolationCode',
#                 'zeeland_gld.TypeMeasementInstrumentType',
#                 'zeeland_gld.TypeObservationType',
#                 'zeeland_gld.TypeProcessReference',
#                 'zeeland_gld.TypeProcessType',
#                 'zeeland_gld.TypeStatusCode',
#                 'zeeland_gld.TypeStatusQualityControl')
#     } 
# )

# Mail configuration
DEFAULT_FROM_EMAIL = 'emile.debadts1@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'emile.debadts1@gmail.com'
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# # BROCONVERTER SETTINGS
GLD_AANLEVERING_SETTINGS = {
    'acces_token_bro_portal': {
        'user':'2f382895e91a|27376655|630',
        'pass':'84d0049b0bb9eb0924fa88f4472e3222eed1c56b0111c9b927c81d2c77df67c9'
    },
    'organisation':'nens',
    'env':'demo',
    'monitoringnetworks':None,
    'failed_dir_gld_registration':os.path.join(BASE_DIR,'failed/gld_aanlevering/gld_startregistration'),
    'failed_dir_gld_addition':os.path.join(BASE_DIR,'failed/_nens_demo/gld_addition'),
    'additions_dir':os.path.join(BASE_DIR, 'gld_aanlevering/additions'),
    'startregistrations_dir':os.path.join(BASE_DIR, 'gld_aanlevering/startregistrations'),
    'delivery_retry_attempts': 3,
    'warning_mail_recipient': 'emile.debadts@nelen-schuurmans.nl',
    'validation_mapping_table':{'WNS9040.val':{'2':'goedgekeurd','5':'onbeslist','8':'afgekeurd','9':'goedgekeurd'},'WNS9040':{'9':'nogNietBeoordeeld'}, 'WNS9040.hand':{'9':'goedgekeurd'}},
    'expiration_log_messages':1000
}

