# Generated by Django 4.0.3 on 2023-11-24 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='collision_protection',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('palen', 'palen'), ('hekwerk', 'hekwerk'), ('onbekend', 'onbekend')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='foundation',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('betonomstorting', 'betonomstorting'), ('onbekend', 'onbekend')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='key',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='label',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('sticker', 'sticker'), ('aluplaatje', 'aluplaatje'), ('onbekend', 'onbekend')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='location_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='lock',
            field=models.CharField(blank=True, choices=[('sleutel', 'sleutel'), ('inbus', 'inbus'), ('onbekend', 'onbekend')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='place',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='remark',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='street',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwelldynamic',
            name='well_head_protector_subtype',
            field=models.CharField(blank=True, choices=[('DNS', 'DNS'), ('model X', 'model X'), ('onbekend', 'onbekend')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwellstatic',
            name='construction_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=28992),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwellstatic',
            name='last_horizontal_positioning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
