# Generated by Django 4.0.3 on 2023-11-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0002_groundwatermonitoringwelldynamic_collision_protection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='groundwater_monitoring_tube',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='groundwater_monitoring_well',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='picture',
        ),
        migrations.DeleteModel(
            name='MaintenanceParty',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='groundwater_monitoring_well',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
