# Generated by Django 4.0.3 on 2023-11-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0003_remove_maintenance_groundwater_monitoring_tube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceParty',
            fields=[
                ('maintenance_party_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('adress', models.CharField(blank=True, max_length=254, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('mobilephone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Onderhoudsteam',
                'verbose_name_plural': 'Onderhoudsteams',
                'db_table': 'gmw"."maintenance_party',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('groundwater_monitoring_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw.groundwatermonitoringwellstatic')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'gmw"."pictures',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('kind_of_maintenance', models.CharField(choices=[], max_length=254)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('reporter', models.IntegerField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('execution_by', models.IntegerField(blank=True, null=True)),
                ('groundwater_monitoring_tube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw.groundwatermonitoringtubesstatic')),
                ('groundwater_monitoring_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw.groundwatermonitoringwellstatic')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw.picture')),
            ],
            options={
                'verbose_name': 'Onderhoudsmoment',
                'verbose_name_plural': 'Onderhoudsmomenten',
                'db_table': 'gmw"."maintenance',
            },
        ),
    ]
