# Generated by Django 4.0.3 on 2023-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0004_maintenanceparty_picture_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwatermonitoringwellstatic',
            name='in_management',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='ground_level_positioning_method',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='ground_level_stable',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='well_head_protector',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='well_stability',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='construction_standard',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='delivery_context',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='horizontal_positioning_method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='initial_function',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='local_vertical_reference_point',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='quality_regime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='reference_system',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='registration_object_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='under_privilege',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='vertical_datum',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
