# Generated by Django 4.0.3 on 2023-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0005_groundwatermonitoringwellstatic_in_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodedynamic',
            name='electrode_status',
            field=models.CharField(blank=True, choices=[('onbruikbaar', 'onbruikbaar'), ('gebruiksklaar', 'gebruiksklaar'), ('nietGebruiksklaar', 'nietGebruiksklaar'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrodestatic',
            name='electrode_packing_material',
            field=models.CharField(blank=True, choices=[('filtergrind', 'filtergrind'), ('klei', 'klei'), ('volgensGerelateerdeVerkenning', 'volgensGerelateerdeVerkenning'), ('zand', 'zand'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrodestatic',
            name='electrode_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, choices=[('beschermconstructieVeranderd', 'beschermconstructieVeranderd'), ('buisdeelIngeplaatst', 'buisdeelIngeplaatst'), ('buisIngekort', 'buisIngekort'), ('buisOpgelengd', 'buisOpgelengd'), ('buisstatusVeranderd', 'buisstatusVeranderd'), ('eigenaarVeranderd', 'eigenaarVeranderd'), ('elektrodestatusVeranderd', 'elektrodestatusVeranderd'), ('maaiveldVerlegd', 'maaiveldVerlegd'), ('nieuweBepalingMaaiveld', 'nieuweBepalingMaaiveld'), ('nieuweBepalingPosities', 'nieuweBepalingPosities'), ('nieuweInmetingMaaiveld', 'nieuweInmetingMaaiveld'), ('nieuweInmetingPosities', 'nieuweInmetingPosities'), ('onderhouderVeranderd', 'onderhouderVeranderd'), ('verkenningenAchterafRegistreren', 'verkenningenAchterafRegistreren')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='glue',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('ongespecificeerd', 'ongespecificeerd'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='inserted_part_material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='tube_packing_material',
            field=models.CharField(blank=True, choices=[('bentoniet', 'bentoniet'), ('bentonietFiltergrind', 'bentonietFiltergrind'), ('boorgatmateriaal', 'boorgatmateriaal'), ('filtergrind', 'filtergrind'), ('grind', 'grind'), ('grout', 'grout'), ('volgensGerelateerdeVerkenning', 'volgensGerelateerdeVerkenning'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='tube_status',
            field=models.CharField(blank=True, choices=[('onbruikbaar', 'onbruikbaar'), ('gebruiksklaar', 'gebruiksklaar'), ('nietGebruiksklaar', 'nietGebruiksklaar'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='tube_top_positioning_method',
            field=models.CharField(blank=True, choices=[('afgeleidSbl', 'afgeleidSbl'), ('AHN2', 'AHN2'), ('AHN3', 'AHN3'), ('RTKGPS0tot4cm', 'RTKGPS0tot4cm'), ('RTKGPS4tot10cm', 'RTKGPS4tot10cm'), ('RTKGPS10tot20cm', 'RTKGPS10tot20cm'), ('RTKGPS20tot100cm', 'RTKGPS20tot100cm'), ('tachymetrie0tot10cm', 'tachymetrie0tot10cm'), ('tachymetrie10tot50cm', 'tachymetrie10tot50cm'), ('waterpassing0tot2cm', 'waterpassing0tot2cm'), ('waterpassing2tot4cm', 'waterpassing2tot4cm'), ('waterpassing4tot10cm', 'waterpassing4tot10cm'), ('AHN1', 'AHN1'), ('GPSOnbekend', 'GPSOnbekend'), ('kaartOnbekend', 'kaartOnbekend'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='sock_material',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('kopergaas', 'kopergaas'), ('nylon', 'nylon'), ('pp', 'pp'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='tube_material',
            field=models.CharField(blank=True, choices=[('beton', 'beton'), ('gres', 'gres'), ('hout', 'hout'), ('ijzer', 'ijzer'), ('koper', 'koper'), ('messing', 'messing'), ('pe', 'pe'), ('peHighDensity', 'peHighDensity'), ('peLowDensity', 'peLowDensity'), ('peHighDensityPvc', 'peHighDensityPvc'), ('pePvc', 'pePvc'), ('pvc', 'pvc'), ('staal', 'staal'), ('staalGegalvaniseerd', 'staalGegalvaniseerd'), ('staalRoestvrij', 'staalRoestvrij'), ('teflon', 'teflon'), ('asbest', 'asbest'), ('houtStaal', 'houtStaal'), ('koperStaal', 'koperStaal'), ('onbekend', 'onbekend'), ('pvcStaal', 'pvcStaal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='tube_type',
            field=models.CharField(blank=True, choices=[('nietGetransformeerd', 'nietGetransformeerd'), ('RDNAPTRANS2008', 'RDNAPTRANS2008'), ('RDNAPTRANS2018', 'RDNAPTRANS2018'), ('RDNAPTRANS2008MV0', 'RDNAPTRANS2008MV0'), ('RDNAPTRANS2018MV0', 'RDNAPTRANS2018MV0')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='ground_level_positioning_method',
            field=models.CharField(blank=True, choices=[('afgeleidBovenkantBuis', 'afgeleidBovenkantBuis'), ('AHN2', 'AHN2'), ('AHN3', 'AHN3'), ('RTKGPS0tot4cm', 'RTKGPS0tot4cm'), ('RTKGPS4tot10cm', 'RTKGPS4tot10cm'), ('RTKGPS10tot20cm', 'RTKGPS10tot20cm'), ('RTKGPS20tot100cm', 'RTKGPS20tot100cm'), ('tachymetrie0tot10cm', 'tachymetrie0tot10cm'), ('tachymetrie10tot50cm', 'tachymetrie10tot50cm'), ('waterpassing0tot2cm', 'waterpassing0tot2cm'), ('waterpassing2tot4cm', 'waterpassing2tot4cm'), ('waterpassing4tot10cm', 'waterpassing4tot10cm'), ('AHN1', 'AHN1'), ('geen', 'geen'), ('GPSOnbekend', 'GPSOnbekend'), ('kaartOnbekend', 'kaartOnbekend'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='well_head_protector',
            field=models.CharField(blank=True, choices=[('geen', 'geen'), ('kokerDeelsMetaal', 'kokerDeelsMetaal'), ('kokerMetaal', 'kokerMetaal'), ('kokerNietMetaal', 'kokerNietMetaal'), ('potNietWaterdicht', 'potNietWaterdicht'), ('potWaterdicht', 'potWaterdicht'), ('koker', 'koker'), ('onbekend', 'onbekend'), ('pot', 'pot')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwelldynamic',
            name='well_stability',
            field=models.CharField(blank=True, choices=[('instabiel', 'instabiel'), ('stabielNAP', 'stabielNAP'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='construction_standard',
            field=models.CharField(blank=True, choices=[('BWsb', 'BWsb'), ('geen', 'geen'), ('IBR', 'IBR'), ('NEN5104', 'NEN5104'), ('NEN5744', 'NEN5744'), ('NEN5766', 'NEN5766'), ('RWSgwmon', 'RWSgwmon'), ('SIKB2001v6.0', 'SIKB2001v6.0'), ('STOWAgwst', 'STOWAgwst'), ('VKB2001', 'VKB2001'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='delivery_context',
            field=models.CharField(blank=True, choices=[('GBM', 'GBM'), ('KRW', 'KRW'), ('monitoringBijDrinkwaterwinning', 'monitoringBijDrinkwaterwinning'), ('NBW', 'NBW'), ('NR', 'NR'), ('OGW', 'OGW'), ('OG', 'OW'), ('publiekeTaak', 'publiekeTaak'), ('WW', 'WW'), ('archiefoverdracht', 'archiefoverdracht')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='horizontal_positioning_method',
            field=models.CharField(blank=True, choices=[('DGPS50tot200cm', 'DGPS50tot200cm'), ('GPS200tot1000cm', 'GPS200tot1000cm'), ('RTKGPS0tot2cm', 'RTKGPS0tot2cm'), ('RTKGPS2tot5cm', 'RTKGPS2tot5cm'), ('RTKGPS5tot10cm', 'RTKGPS5tot10cm'), ('RTKGPS10tot50cm', 'RTKGPS10tot50cm'), ('tachymetrie0tot10cm', 'tachymetrie0tot10cm'), ('tachymetrie10tot50cm', 'tachymetrie10tot50cm'), ('GBKNOnbekend', 'GBKNOnbekend'), ('GPSOnbekend', 'GPSOnbekend'), ('kaartOnbekend', 'kaartOnbekend'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='initial_function',
            field=models.CharField(blank=True, choices=[('brandput', 'brandput'), ('kwaliteit', 'kwaliteit'), ('kwaliteitStand', 'kwaliteitStand'), ('onttrekking', 'onttrekking'), ('stand', 'stand'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='local_vertical_reference_point',
            field=models.CharField(blank=True, choices=[('NAP', 'NAP')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwellstatic',
            name='vertical_datum',
            field=models.CharField(blank=True, choices=[('NAP', 'NAP')], max_length=200, null=True),
        ),
    ]
