# Generated by Django 4.0.3 on 2023-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0006_alter_electrodedynamic_electrode_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='bulk')),
                ('report', models.TextField(blank=True, help_text='process description', null=True)),
                ('checked', models.BooleanField(blank=True, default=False, editable=False, help_text='checked', null=True)),
                ('imported', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='fully imported')),
            ],
            options={
                'verbose_name': 'XML import',
                'verbose_name_plural': 'XML imports',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, choices=[('constructie', 'constructie'), ('beschermconstructieVeranderd', 'beschermconstructieVeranderd'), ('buisdeelIngeplaatst', 'buisdeelIngeplaatst'), ('buisIngekort', 'buisIngekort'), ('buisOpgelengd', 'buisOpgelengd'), ('buisstatusVeranderd', 'buisstatusVeranderd'), ('eigenaarVeranderd', 'eigenaarVeranderd'), ('elektrodestatusVeranderd', 'elektrodestatusVeranderd'), ('maaiveldVerlegd', 'maaiveldVerlegd'), ('nieuweBepalingMaaiveld', 'nieuweBepalingMaaiveld'), ('nieuweBepalingPosities', 'nieuweBepalingPosities'), ('nieuweInmetingMaaiveld', 'nieuweInmetingMaaiveld'), ('nieuweInmetingPosities', 'nieuweInmetingPosities'), ('onderhouderVeranderd', 'onderhouderVeranderd'), ('verkenningenAchterafRegistreren', 'verkenningenAchterafRegistreren')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='variable_diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
