# Generated by Django 4.0.3 on 2023-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0007_xmlimport_alter_event_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='artesian_well_cap_present',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='sediment_sump_present',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
