"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import platform
from pathlib import Path

import django.db.models.options as options
import pytz
from main.localsecret import ENV, GDAL_DLL_VERSION

options.DEFAULT_NAMES = options.DEFAULT_NAMES + ("schema",)

# Application definition
MODULES = ["gmw", "frd", "gld", "gmn", "gar"]


POLYGON_SHAPEFILE = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "data"
    / "shapefile"
    / "ProvincieZeeland_BrabantseWal_GeoNAM.shp"
)

KVK_USER = "20168636"

USE_WELLS_AS_MAP_CENTER = True
MAP_CENTER = [3.945697, 51.522601]
MAP_ZOOM = 9

CACHE_TIMEOUT = 60 * 60 * 24  # 1 day

##### CUSTOMIZEABLE SETTINGS FOR EXPERIENCED USERS #####

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1b2-79o0!+@%9d6gt@7k5-8=8(r@&x-(15!o7+zo-zgwg4)gbv"

ALLOWED_HOSTS = ["*"]

# Optional canonical external origin used by embedded services (e.g. GWDatalens)
# to construct absolute callback/API URLs.
BRO_CONNECTOR_BASE_URL = None

INSTALLED_APPS = [
    "jazzmin",
    "main",
    "bro",
    "gld",
    "gmw",
    "gmn",
    "frd",
    "gar",
    "tools",
    "rest_framework",
    "reversion",
    "reversion_compare",
    "admin_reorder",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_admin_generator",
    "image_uploader_widget",
    "django_extensions",
    "django_plotly_dash.apps.DjangoPlotlyDashConfig",
    "django_static_jquery",
    "admin_auto_filters",
    "dpd_static_support",
    "bootstrap4",
]


MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        # ("mapCenterLocationName", "london"),
        (
            "GooglePlaceAutocompleteOptions",
            {"componentRestrictions": {"country": "netherlands"}},
        ),
        ("markerFitZoom", 12),
    ),
    "GOOGLE_MAP_API_KEY": "<google-api-key>",
}

# Caching configuration: file-based cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": f"{BASE_DIR}/.cache",  # You can change this path if needed
        "TIMEOUT": 3600,  # 1 hour
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "CULL_FREQUENCY": 3,
        },
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.db"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "admin_reorder.middleware.ModelAdminReorder",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "main.settings.user.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "reversion.middleware.RevisionMiddleware",
    "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
    "django_plotly_dash.middleware.BaseMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [f"{BASE_DIR}/main/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"

# Dummy Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "",
        "USER": "",
        "PASSWORD": "",
        "HOST": "",
        "PORT": "",
        "OPTIONS": {"options": "-c search_path=django_admin,public,gmw,bro"},
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Amsterdam"
TZINFO = pytz.timezone(TIME_ZONE)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_FILES_LOCATION = "static"
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


X_FRAME_OPTIONS = "SAMEORIGIN"

PLOTLY_COMPONENTS = [
    "dpd_static_support",
    "dpd_components",
    "dash_bootstrap_components",
]

PLOTLY_DASH = {
    "ws_route": "dpd/ws/channel",
    "http_route": "dpd/views",
    "http_poke_enabled": True,
    "insert_demo_migrations": False,
    "cache_timeout_initial_arguments": 60,
    "view_decorator": None,
    "cache_arguments": False,
    "serve_locally": False,
}

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django_plotly_dash.finders.DashAssetFinder",
    "django_plotly_dash.finders.DashComponentFinder",
    "django_plotly_dash.finders.DashAppDirectoryFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ADMIN_REORDER = (
    {
        "app": "gmn",
        "label": "Grondwatermonitoringnet (GMN)",
        "models": (
            "gmn.GroundwaterMonitoringNet",
            "gmn.Subgroup",
            "gmn.MeasuringPoint",
            "gmn.IntermediateEvent",
            "gmn.gmn_bro_sync_log",
        ),
    },
    {
        "app": "bro",
        "label": "BRO",
    },
    {
        "app": "gmw",
        "label": "Grondwatermonitoringput (GMW)",  # Provincie Zeeland GWM - Data
        "models": (
            "gmw.GroundwaterMonitoringWellStatic",
            "gmw.GroundwaterMonitoringWellDynamic",
            "gmw.GroundwaterMonitoringTubeStatic",
            "gmw.GroundwaterMonitoringTubeDynamic",
            "gmw.GeoOhmCable",
            "gmw.Electrode",
            "gmw.Event",
            "gmw.MaintenanceParty",
            "gmw.Maintenance",
            "gmw.RelatedSurvey",
            "gmw.gmw_registration_log",
        ),
    },
    {
        "app": "tools",
        "label": "Tools",
    },
    {
        "app": "gld",
        "label": "Grondwaterstandsonderzoek (GLD)",
        "models": (
            "gld.GroundwaterLevelDossier",
            "gld.Observation",
            "gld.ObservationProcess",
            "gld.ObservationMetadata",
            "gld.MeasurementTvp",
            "gld.MeasurementPointMetadata",
            "gld.gld_registration_log",
            "gld.gld_addition_log",
        ),
    },
    {
        "app": "frd",
        "label": "Formatieweestand (FRD)",
        "models": (
            "frd.FormationResistanceDossier",
            "frd.CalculatedFormationresistanceMethod",
            "frd.FormationresistanceSeries",
            "frd.FormationresistanceRecord",
            "frd.GeoOhmMeasurementMethod",
            "frd.ElectromagneticMeasurementMethod",
            "frd.InstrumentConfiguration",
            "frd.MeasurementConfiguration",
            "frd.ElectrodePair",
            "frd.GMWElectodeReference",
            "frd.ElectromagneticSeries",
            "frd.ElectromagneticRecord",
            "frd.GeoOhmMeasurementValue",
            "frd.FrdSyncLog",
        ),
    },
    {
        "app": "gar",
        "label": "Grondwatersamenstellingsonderzoek (GAR)",  # Provincie Zeeland GWM - Data
        "models": (
            "gar.Analysis",
            "gar.AnalysisProcesses",
            "gar.FieldMeasurement",
            "gar.FieldObservations",
            "gar.FieldSamples",
            "gar.GroundwaterCompositionResearches",
            "gar.LaboratoryAnalyses",
            "gar.StoffenGroepen",
            "gar.TypeColourStrengths",
            "gar.TypeColours",
            "gar.TypeParameterlijsten",
            "gar.TypeWaardebepalingsmethodes",
        ),
    },
)


LOG_DIR = "/var/logs"
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "detailed": {
            "format": "%(asctime)s: %(name)s %(levelname)s %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "task_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "task.log"),
            "formatter": "detailed",
        },
        "access_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "access.log"),
            "formatter": "detailed",
        },
        "general_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "general.log"),
            "formatter": "detailed",
        },
    },
    "loggers": {
        "task": {
            "handlers": ["task_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "access": {
            "handlers": ["access_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "general": {
            "handlers": ["general_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if ENV == "production":
    demo = False
    welcome_sign = "Inloggen"
else:
    demo = True
    welcome_sign = "Inloggen (testomgeving)"

# # BROCONVERTER SETTINGS
gld_SETTINGS = {
    "additions_dir": os.path.join(BASE_DIR, "gld\\additions"),
    "startregistrations_dir": os.path.join(BASE_DIR, "gld\\startregistrations"),
}

gmw_SETTINGS = {
    "registrations_dir": os.path.join(BASE_DIR, "gmw\\registrations"),
}

gmn_SETTINGS = {
    "monitoringnetworks": None,
    "additions_dir": os.path.join(BASE_DIR, "gmn\\additions"),
    "registrations_dir": os.path.join(BASE_DIR, "gmn\\registrations"),
    "removals_dir": os.path.join(BASE_DIR, "gmn\\removals"),
    "closures_dir": os.path.join(BASE_DIR, "gmn\\closures"),
}

# Quick Scan SETTINGS
QUICK_SCAN_SETTINGS = {
    "jump_slope_limit": 1 / (60 * 60),  # m/s (1/3600 m/s = 1 m/h)
    # 'max_change_two_measurements':1,
    # 'liveliness_maximum_flatline_duration':100
}

JAZZMIN_SETTINGS = {
    # "site_logo": os.path.join(BASE_DIR, "static/img/broconnector.png"),
    "site_logo": "img/broconnector.png",
    "welcome_sign": welcome_sign,
    "custom_css": "css/jazzmin_custom.css",
    # Links to put along the top menu
    "topmenu_links": [
        # model admin to link to (Permissions checked against model)
        {"name": "Kaart", "url": "/map", "permissions": ["auth.view_user"]},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "bro"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "gmw"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "gmn"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "gld"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "frd"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "gar"},
        # gwdatalens app
        {"name": "GWDataLens", "url": "/gwdatalens", "permissions": ["auth.view_user"]},
    ],
    "usermenu_links": [
        {
            "name": "Support",
            "url": "https://github.com/nens/bro-connector",
            "new_window": True,
        },
        {"model": "auth.user"},
    ],
    # Whether to aut expand the menu
    "navigation_expanded": False,
    "order_with_respect_to": [
        "auth",
        "bro",
        "gmn",
        "gmn.GroundwaterMonitoringNet",
        "gmn.Subgroup",
        "gmn.MeasuringPoint",
        "gmn.IntermediateEvent",
        "gmn.gmn_bro_sync_log",
        "gmw",
        "gmw.GroundwaterMonitoringWellStatic",
        "gmw.GroundwaterMonitoringWellDynamic",
        "gmw.GroundwaterMonitoringTubeStatic",
        "gmw.GroundwaterMonitoringTubeDynamic",
        "gmw.GeoOhmCable",
        "gmw.Electrode",
        "gmw.Event",
        "gmw.MaintenanceParty",
        "gmw.Maintenance",
        "gmw.RelatedSurvey",
        "gld",
        "gld.GroundwaterLevelDossier",
        "gld.Observation",
        "gld.ObservationProcess",
        "gld.ObservationMetadata",
        "gld.MeasurementTvp",
        "gld.MeasurementPointMetadata",
        "gld.gld_registration_log",
        "gld.gld_addition_log",
        "frd",
        "frd.FormationResistanceDossier",
        "frd.GMWElectodeReference",
        "frd.ElectrodePair",
        "frd.MeasurementConfiguration",
        "frd.GeoOhmMeasurementMethod",
        "frd.GeoOhmMeasurementValue",
        "frd.CalculatedFormationresistanceMethod",
        "frd.FormationresistanceSeries",
        "frd.FormationresistanceRecord",
        "frd.InstrumentConfiguration",
        "frd.ElectromagneticMeasurementMethod",
        "frd.ElectromagneticSeries",
        "frd.ElectromagneticRecord",
        "frd.FrdSyncLog",
        "gar",
        "gar.GroundwaterCompositionResearches",
        "gar.FieldObservations",
        "gar.FieldMeasurements",
        "gar.FieldSamples",
        "gar.LaboratoryAnalyses",
        "gar.AnalysisProcesses",
        "gar.Analysis",
        "gar.Combi",
        "gar.StoffenGroepen",
        "gar.TypeColourStrengths",
        "gar.TypeColours",
        "gar.TypeParameterlijsten",
        "gar.TypeWaardebepalingsmethodes",
        "tools",
    ],
    "show_ui_builder": False,
    "icons": {
        "auth": "fa-solid fa-users-gear",
        "auth.user": "fa-solid fa-user",
        "auth.Group": "fa-solid fa-users",
        "gld": "fa-solid fa-book-open",
        "gld.gld_registration_log": "fa-solid fa-book",
        "gld.gld_addition_log": "fa-solid fa-book-medical",
        "gld.Observation": "fa-solid fa-search-location",
        "gld.GroundwaterLevelDossier": "fa-solid fa-folder",
        "gld.MeasurementPointMetadata": "fa-solid fa-circle-info",
        "gld.MeasurementTvp": "fa-solid fa-right-left",
        "gld.ObservationMetadata": "fa-solid fa-circle-info",
        "gld.ResponsibleParty": "fa-solid fa-building",
        "gld.TypeAirPressureCompensation": "fa-solid fa-book-open",
        "gld.TypeCensoredReasonCode": "fa-solid fa-book-open",
        "gld.TypeEvaluationProcedure": "fa-solid fa-book-open",
        "gld.TypeInterpolationCode": "fa-solid fa-book-open",
        "gld.TypeMeasurementInstrumentType": "fa-solid fa-book-open",
        "gld.TypeObservationType": "fa-solid fa-book-open",
        "gld.TypeProcessReference": "fa-solid fa-book-open",
        "gld.TypeProcessType": "fa-solid fa-book-open",
        "gld.TypeStatusCode": "fa-solid fa-book-open",
        "gld.ObservationProcess": "fa-solid fa-book-open",
        "gld.TypeStatusQualityControl": "fa-solid fa-book-open",
        "gmw": "fa-solid fa-search-location",
        "gmw.GroundwaterMonitoringWellStatic": "fa-solid fa-ruler-vertical",
        "gmw.GroundwaterMonitoringWellDynamic": "fa-solid fa-ruler-vertical",
        "gmw.GroundwaterMonitoringTubeStatic": "fa-solid fa-vials",
        "gmw.GroundwaterMonitoringTubeDynamic": "fa-solid fa-vials",
        "gmw.GeoOhmCable": "fa-solid fa-ethernet",
        "gmw.Electrode": "fa-solid fa-bolt",
        "gmw.Event": "fa-solid fa-book-open",
        "gmw.Instantie": "fa-solid fa-building",
        "gmn": "fa-regular fa-object-group",
        "gmn.GroundwaterMonitoringNet": "fa-solid fa-diagram-project",
        "gmn.Subgroup": "fa-solid fa-diagram-project",
        "gmn.MeasuringPoint": "fa-solid fa-ruler-vertical",
        "gmn.IntermediateEvent": "fa-solid fa-calendar",
        "gmn.gmn_bro_sync_log": "fa-solid fa-arrows-rotate",
        "frd": "fa-regular fa-bolt",
        "frd.FormationResistanceDossier": "fa-solid fa-folder",
        "frd.InstrumentConfiguration": "fa-solid fa-server",
        "frd.ElectromagneticMeasurementMethod": "fa-solid fa-book-open",
        "frd.GeoOhmMeasurementMethod": "fa-solid fa-book-open",
        "frd.GeoOhmMeasurementValue": "fa-solid fa-chart-line",
        "frd.ElectrodePair": "fa-solid fa-vials",
        "frd.MeasurementConfiguration": "fa-solid fa-server",
        "frd.ElectromagneticSeries": "fa-solid fa-book-open",
        "frd.FormationresistanceSeries": "fa-solid fa-book-open",
        "frd.ElectromagneticRecord": "fa-solid fa-chart-line",
        "frd.FormationresistanceRecord": "fa-solid fa-chart-line",
        # "gmw.GroundwaterMonitoringTubes": "fa-solid fa-prescription-bottle",
        "tools": "fa-solid fa-wrench",
    },
    "changeform_format_overrides": {"gmw.GroundwaterMonitoringWellStatic": "tab"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}

DATA_UPLOAD_MAX_MEMORY_SIZE = int(10_485_760 * 1.5)  # (15MB) needed for DASH APP

if platform.system() == "Windows":
    GDAL_LIBRARY_PATH = rf"C:\OSGeo4W\bin\gdal{GDAL_DLL_VERSION}.dll"
    GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"
