"""
Django settings for bro_converter project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from main.settings.base import *

DEBUG = True
ROOT_URLCONF = "main.urls"
SECRET_KEY = "django-insecure-3%@hi=c5i_&u!13p33w4kymt40zht9zhqa8*dty$8gp%ph#7@!"

DATABASES = {
    "default": {
        "NAME": database,
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "USER": s_user,
        "PASSWORD": s_password,
        "HOST": s_host,
        "PORT": s_port,
        "OPTIONS": {"options": "-c search_path=django_admin,public"},
    },
}

LIZARD_SETTINGS = {
    "headers": {
        "username": "{}".format("__key__"),
        "password": f"{validation_key}",
        "Content-Type": "application/json",
    },
    "organisation_uuid": "e7d66583-43b2-4c90-b118-f2093798885a",
    "site_url": "https://nens.lizard.net",
}

