"""
Django settings for bro_converter project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from main.settings.base import *

DEBUG = True
ROOT_URLCONF = "main.urls"
SECRET_KEY = "django-insecure-3%@hi=c5i_&u!13p33w4kymt40zht9zhqa8*dty$8gp%ph#7@!"

CSRF_TRUSTED_ORIGINS = [
    "https://bro-prod.zeeland.nl/",
    "https://bro-prod.zeeland.nl/admin",
]


SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

DATABASES = {
    "default": {
        "NAME": "grondwatermeetnet",
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "USER": t_user,
        "PASSWORD": t_password,
        "HOST": t_host,
        "PORT": t_port,
        "OPTIONS": {"options": "-c search_path=django_admin,public,gmw"},
    },
}
