# Generated by Django 4.0.3 on 2022-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveredlocations',
            old_name='registration_object_id',
            new_name='groundwater_monitoring_well_id',
        ),
        migrations.RenameField(
            model_name='deliveredverticalpositions',
            old_name='registration_object_id',
            new_name='groundwater_monitoring_well_id',
        ),
        migrations.RenameField(
            model_name='deliveredverticalpositions',
            old_name='delivered_vertical_positions_id',
            new_name='vertical_position_id',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringtubes',
            old_name='registration_object_id',
            new_name='groundwater_monitoring_well_id',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringwells',
            old_name='registration_object_id',
            new_name='groundwater_monitoring_well_id',
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwells',
            name='delivered_to_bro',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwells',
            name='monitoring_pdok_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwells',
            name='well_removal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
