# Generated by Django 4.0.3 on 2022-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0003_delete_gld_addition_log_delete_gld_registration_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='gld_addition_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.CharField(blank=True, max_length=254, null=True)),
                ('observation_id', models.CharField(blank=True, max_length=254, null=True)),
                ('start', models.CharField(blank=True, max_length=254, null=True)),
                ('end', models.CharField(blank=True, max_length=254, null=True)),
                ('broid_registration', models.CharField(blank=True, max_length=254, null=True)),
                ('procedure_uuid', models.CharField(blank=True, max_length=254, null=True)),
                ('procedure_initialized', models.CharField(blank=True, max_length=254, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_id', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_status', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.CharField(blank=True, max_length=50000, null=True)),
                ('file', models.CharField(blank=True, max_length=254, null=True)),
                ('addition_type', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'GLD addition logging',
                'verbose_name_plural': 'GLD addition logging',
                'db_table': 'aanlevering"."gld_addition_log',
            },
        ),
        migrations.CreateModel(
            name='gld_registration_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_modified', models.CharField(blank=True, max_length=254, null=True)),
                ('gwm_bro_id', models.CharField(blank=True, max_length=254, null=True)),
                ('filter_id', models.CharField(blank=True, max_length=254, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_id', models.CharField(blank=True, max_length=254, null=True)),
                ('levering_status', models.CharField(blank=True, max_length=254, null=True)),
                ('gld_bro_id', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('last_changed', models.CharField(blank=True, max_length=254, null=True)),
                ('corrections_applied', models.BooleanField(blank=True, null=True)),
                ('timestamp_end_registration', models.DateTimeField(blank=True, null=True)),
                ('quality_regime', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.CharField(blank=True, max_length=254, null=True)),
                ('process_status', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'GLD registration logging',
                'verbose_name_plural': 'GLD registration logging',
                'db_table': 'aanlevering"."gld_registration_log',
            },
        ),
    ]
