# Generated by Django 4.0.3 on 2022-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld_aanlevering', '0004_gld_addition_log_gld_registration_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringtubes',
            name='deliver_to_bro',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwells',
            name='delivered_to_bro',
            field=models.BooleanField(default=False),
        ),
    ]
