name: BRO-Connector Request
description: Request a new feature or enhancement for the BRO-Connector
title: "[BRO-Connector][Request]: "
labels:
  - bro-connector
  - enhancement
assignees:
  - jzitman
body:
  - type: input
    id: bro_type
    attributes:
      label: BRO Domain
      description: Specify the BRO domain (e.g., GMW, GLD, GAR, GMN, FRD).
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement.
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Why is this useful?
      description: What problem does this solve?
    validations:
      required: false

  - type: input
    id: priority
    attributes:
      label: Priority or urgency
      description: Optional – low / medium / high
    validations:
      required: false
