name: GWDataLens Issue
description: Report a bug or problem with GWDataLens
title: "[GWDataLens][Bug]: "
labels:
  - gwdatalens
  - bug
assignees:
  - dbrakenhoff
body:
  - type: textarea
    id: problem
    attributes:
      label: What is the issue?
      description: Describe the problem you are encountering.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: context
    attributes:
      label: Context
      description: Dataset, screen, or workflow involved
    validations:
      required: false
