# Generated by Django 4.0.3 on 2023-07-31 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterMonitoringWellStatic',
            fields=[
                ('groundwater_monitoring_well_static_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_object_type', models.TextField(blank=True, null=True)),
                ('bro_id', models.CharField(blank=True, max_length=15, null=True)),
                ('request_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_accountable_party', models.IntegerField(blank=True, null=True)),
                ('delivery_responsible_party', models.IntegerField(blank=True, null=True)),
                ('quality_regime', models.TextField(blank=True, null=True)),
                ('under_privilege', models.TextField(blank=True, null=True)),
                ('delivery_context', models.TextField(blank=True, null=True)),
                ('construction_standard', models.TextField(blank=True, null=True)),
                ('initial_function', models.TextField(blank=True, null=True)),
                ('nitg_code', models.CharField(blank=True, max_length=256, null=True)),
                ('olga_code', models.CharField(blank=True, max_length=256, null=True)),
                ('well_code', models.CharField(blank=True, max_length=256, null=True)),
                ('well_construction_date', models.DateField(blank=True, null=True)),
                ('well_removal_date', models.DateField(blank=True, null=True)),
                ('monitoring_pdok_id', models.IntegerField(blank=True, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=28992)),
                ('referencesystem', models.TextField(blank=True, null=True)),
                ('horizontal_positioning_method', models.TextField(blank=True, null=True)),
                ('local_vertical_reference_point', models.TextField(blank=True, null=True)),
                ('offset', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('vertical_datum', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Groundwater monitoring wells (Static)',
                'db_table': 'gmw"."groundwater_monitoring_well_static',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringWellDynamic',
            fields=[
                ('groundwater_monitoring_well_dynamic_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_standpipes', models.IntegerField(blank=True, null=True)),
                ('ground_level_stable', models.TextField(blank=True, null=True)),
                ('well_stability', models.TextField(blank=True, null=True)),
                ('owner', models.IntegerField(blank=True, null=True)),
                ('maintenance_responsible_party', models.IntegerField(blank=True, null=True)),
                ('well_head_protector', models.TextField(blank=True, null=True)),
                ('delivered_to_bro', models.BooleanField(default=False)),
                ('ground_level_position', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ground_level_positioning_method', models.TextField(blank=True, null=True)),
                ('groundwater_monitoring_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
            ],
            options={
                'verbose_name_plural': 'Groundwater monitoring wells (Dynamic)',
                'db_table': 'gmw"."groundwater_monitoring_well_dynamic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringTubesStatic',
            fields=[
                ('groundwater_monitoring_tube_static_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deliver_to_bro', models.BooleanField(blank=True, default=False)),
                ('tube_number', models.IntegerField(blank=True, null=True)),
                ('tube_type', models.TextField(blank=True, null=True)),
                ('artesian_well_cap_present', models.TextField(blank=True, null=True)),
                ('sediment_sump_present', models.TextField(blank=True, null=True)),
                ('number_of_geo_ohm_cables', models.IntegerField(blank=True, null=True)),
                ('tube_material', models.TextField(blank=True, null=True)),
                ('screen_length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sock_material', models.TextField(blank=True, null=True)),
                ('sediment_sump_length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('groundwater_monitoring_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
            ],
            options={
                'verbose_name_plural': 'Groundwater monitoring tubes (Static)',
                'db_table': 'gmw"."groundwater_monitoring_tubes_static',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringTubesDynamic',
            fields=[
                ('groundwater_monitoring_tube_dynamic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tube_top_diameter', models.IntegerField(blank=True, null=True)),
                ('variable_diameter', models.TextField(blank=True, null=True)),
                ('tube_status', models.TextField(blank=True, null=True)),
                ('tube_top_position', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('tube_top_positioning_method', models.TextField(blank=True, null=True)),
                ('tube_packing_material', models.TextField(blank=True, null=True)),
                ('glue', models.TextField(blank=True, null=True)),
                ('plain_tube_part_length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('inserted_part_diameter', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('inserted_part_length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('inserted_part_material', models.TextField(blank=True, null=True)),
                ('groundwater_monitoring_tube_static_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
            ],
            options={
                'verbose_name_plural': 'Groundwater monitoring tubes (Dynamic)',
                'db_table': 'gmw"."groundwater_monitoring_tubes_dynamic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeoOhmCable',
            fields=[
                ('geo_ohm_cable_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cable_number', models.IntegerField(blank=True, null=True)),
                ('groundwater_monitoring_tube_static_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
            ],
            options={
                'verbose_name_plural': 'Geo Ohm Cable',
                'db_table': 'gmw"."geo_ohm_cable_static',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectrodeStatic',
            fields=[
                ('electrode_static_id', models.IntegerField(primary_key=True, serialize=False)),
                ('electrode_packing_material', models.TextField(blank=True, null=True)),
                ('electrode_positioning', models.TextField(blank=True, null=True)),
                ('geo_ohm_cable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.geoohmcable')),
            ],
            options={
                'verbose_name_plural': 'Electrodes (Static)',
                'db_table': 'gmw"."electrodes_static',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectrodeDynamic',
            fields=[
                ('electrode_dynamic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('electrode_number', models.IntegerField(blank=True, null=True)),
                ('electrode_status', models.TextField(blank=True, null=True)),
                ('electrode_static_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.electrodestatic')),
            ],
            options={
                'verbose_name_plural': 'Electrodes (Dynamic)',
                'db_table': 'gmw"."electrodes_dynamic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('change_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scenario_type', models.TextField(blank=True, null=True)),
                ('change_datetime', models.DateTimeField(blank=True, null=True)),
                ('electrode_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.electrodedynamic')),
                ('groundwater_monitoring_well_static', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
                ('groundwater_monitoring_well_tubes_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringtubesdynamic')),
            ],
            options={
                'verbose_name_plural': 'ChangeLog',
                'db_table': 'gmw"."changelog',
                'managed': True,
            },
        ),
    ]
