# Generated by Django 4.0.3 on 2023-08-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoohmcable',
            name='groundwater_monitoring_tube_static_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringtubesstatic'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='groundwater_monitoring_tube_static_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringtubesstatic'),
        ),
    ]
