# Generated by Django 4.0.3 on 2023-09-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0002_alter_geoohmcable_groundwater_monitoring_tube_static_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('change_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scenario_type', models.TextField(blank=True, null=True)),
                ('change_datetime', models.DateTimeField(blank=True, null=True)),
                ('electrode_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.electrodedynamic')),
                ('groundwater_monitoring_well_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwelldynamic')),
                ('groundwater_monitoring_well_static', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringwellstatic')),
                ('groundwater_monitoring_well_tubes_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw_aanlevering.groundwatermonitoringtubesdynamic')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'gmw"."event',
                'managed': True,
            },
        ),
       
    ]
