# Generated by Django 4.0.3 on 2023-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0003_event_delete_changelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrodedynamic',
            old_name='electrode_static_id',
            new_name='electrode_static',
        ),
        migrations.RenameField(
            model_name='electrodestatic',
            old_name='geo_ohm_cable_id',
            new_name='geo_ohm_cable',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='change_datetime',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='scenario_type',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='groundwater_monitoring_well_tubes_dynamic',
            new_name='groundwater_monitoring_well_tube_dynamic',
        ),
        migrations.RenameField(
            model_name='geoohmcable',
            old_name='groundwater_monitoring_tube_static_id',
            new_name='groundwater_monitoring_tube_static',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringtubesdynamic',
            old_name='groundwater_monitoring_tube_static_id',
            new_name='groundwater_monitoring_tube_static',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringwellstatic',
            old_name='referencesystem',
            new_name='reference_system',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringwellstatic',
            old_name='offset',
            new_name='well_offset',
        ),
        migrations.AlterField(
            model_name='electrodedynamic',
            name='electrode_dynamic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='electrodestatic',
            name='electrode_static_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='change_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoohmcable',
            name='geo_ohm_cable_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesdynamic',
            name='groundwater_monitoring_tube_dynamic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringtubesstatic',
            name='groundwater_monitoring_tube_static_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
