# Generated by Django 4.0.3 on 2023-09-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0004_rename_electrode_static_id_electrodedynamic_electrode_static_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundwatermonitoringwellstatic',
            name='well_construction_date',
        ),
        migrations.RemoveField(
            model_name='groundwatermonitoringwellstatic',
            name='well_removal_date',
        ),
    ]
