# Generated by Django 4.0.3 on 2023-09-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0005_remove_groundwatermonitoringwellstatic_well_construction_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrodestatic',
            old_name='electrode_positioning',
            new_name='electrode_position',
        ),
    ]
