# Generated by Django 4.0.3 on 2023-09-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmw_aanlevering', '0006_rename_electrode_positioning_electrodestatic_electrode_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundwatermonitoringtubesstatic',
            old_name='deliver_to_bro',
            new_name='deliver_gld_to_bro',
        ),
        migrations.RenameField(
            model_name='groundwatermonitoringwelldynamic',
            old_name='delivered_to_bro',
            new_name='deliver_gld_to_bro',
        ),
    ]
