# Generated by Django 4.0.3 on 2023-11-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frd_aanlevering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electrodepair',
            options={'managed': True, 'verbose_name_plural': 'Electrode Pair'},
        ),
        migrations.AlterModelOptions(
            name='electromagneticmeasurementmethod',
            options={'managed': True, 'verbose_name_plural': 'Electromagnetic Measurement Method'},
        ),
        migrations.AlterModelOptions(
            name='electromagneticrecord',
            options={'managed': True, 'verbose_name_plural': 'Electromagnetic Records'},
        ),
        migrations.AlterModelOptions(
            name='electromagneticseries',
            options={'managed': True, 'verbose_name_plural': 'Electromagnetic Series'},
        ),
        migrations.AlterModelOptions(
            name='formationresistancedossier',
            options={'managed': True, 'verbose_name': 'Formation Resistance Dossier', 'verbose_name_plural': 'Formation Resistance Dossier'},
        ),
        migrations.AlterModelOptions(
            name='formationresistancerecord',
            options={'managed': True, 'verbose_name_plural': 'Formationresistance Records'},
        ),
        migrations.AlterModelOptions(
            name='formationresistanceseries',
            options={'managed': True, 'verbose_name_plural': 'Formationresistance Series'},
        ),
        migrations.AlterModelOptions(
            name='geoohmmeasurementmethod',
            options={'managed': True, 'verbose_name_plural': 'Geo Ohm Measurement Method'},
        ),
        migrations.AlterModelOptions(
            name='geoohmmeasurementvalue',
            options={'managed': True, 'verbose_name_plural': 'Geo Ohm Measurement Value'},
        ),
        migrations.AlterModelOptions(
            name='gmwelectrodereference',
            options={'managed': True, 'verbose_name_plural': 'GMW Electrode Reference'},
        ),
        migrations.AlterModelOptions(
            name='instrumentconfiguration',
            options={'managed': True, 'verbose_name_plural': 'Instrument Configurations'},
        ),
        migrations.AlterModelOptions(
            name='measurementconfiguration',
            options={'managed': True, 'verbose_name_plural': 'Measurement Configuration'},
        ),
    ]
