# Generated by Django 4.0.3 on 2023-12-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmw', '0008_alter_groundwatermonitoringtubesstatic_artesian_well_cap_present_and_more'),
        ('gmn', '0001_initial'),
        ('frd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electromagneticmeasurementmethod',
            name='measuring_responsible_party',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('elektromagnetischeBepaling', 'elektromagnetischeBepaling'), ('geoohmkabelBepaling', 'geoohmkabelBepaling')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='delivery_accountable_party',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='delivery_responsible_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='electromagnetic_measurement_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frd.electromagneticmeasurementmethod'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='geo_ohm_measurement_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frd.geoohmmeasurementmethod'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='gmn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmn.groundwatermonitoringnet'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='gmw_tube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmw.groundwatermonitoringtubesstatic'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='instrument_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frd.instrumentconfiguration'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='measurement_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frd.measurementconfiguration'),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='object_id_accountable_party',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='quality_regime',
            field=models.CharField(blank=True, choices=[('IMBRO', 'IMBRO'), ('IMBRO/A', 'IMBRO/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geoohmmeasurementmethod',
            name='measuring_responsible_party',
            field=models.CharField(max_length=235),
        ),
    ]
