# Generated by Django 4.0.3 on 2023-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frd', '0002_alter_electromagneticmeasurementmethod_measuring_responsible_party_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoohmmeasurementmethod',
            old_name='measuring_date',
            new_name='measurement_date',
        ),
        migrations.AlterField(
            model_name='formationresistancedossier',
            name='frd_bro_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Bro-ID FRD'),
        ),
    ]
