# Generated by Django 4.0.3 on 2023-11-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementpointmetadata',
            name='censored_reason',
        ),
        migrations.RemoveField(
            model_name='measurementpointmetadata',
            name='interpolation_code',
        ),
        migrations.RemoveField(
            model_name='measurementpointmetadata',
            name='qualifier_by_category',
        ),
        migrations.RemoveField(
            model_name='measurementtvp',
            name='field_value',
        ),
        migrations.RemoveField(
            model_name='measurementtvp',
            name='measurement_point_metadata',
        ),
        migrations.RemoveField(
            model_name='measurementtvp',
            name='measurement_time',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='groundwater_level_dossier',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observation_metadata',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observation_process',
        ),
        migrations.RemoveField(
            model_name='observationmetadata',
            name='parameter_measurement_serie_type',
        ),
        migrations.RemoveField(
            model_name='observationmetadata',
            name='responsible_party',
        ),
        migrations.RemoveField(
            model_name='observationmetadata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='observationprocess',
            name='parameter_air_pressure_compensation_type',
        ),
        migrations.RemoveField(
            model_name='observationprocess',
            name='parameter_evaluation_procedure',
        ),
        migrations.RemoveField(
            model_name='observationprocess',
            name='parameter_measurement_instrument_type',
        ),
        migrations.RemoveField(
            model_name='observationprocess',
            name='process_reference',
        ),
        migrations.RemoveField(
            model_name='observationprocess',
            name='process_type',
        ),
        migrations.DeleteModel(
            name='TypeAirPressureCompensation',
        ),
        migrations.DeleteModel(
            name='TypeCensoredReasonCode',
        ),
        migrations.DeleteModel(
            name='TypeEvaluationProcedure',
        ),
        migrations.DeleteModel(
            name='TypeInterpolationCode',
        ),
        migrations.DeleteModel(
            name='TypeMeasurementInstrumentType',
        ),
        migrations.DeleteModel(
            name='TypeObservationType',
        ),
        migrations.DeleteModel(
            name='TypeProcessReference',
        ),
        migrations.DeleteModel(
            name='TypeProcessType',
        ),
        migrations.DeleteModel(
            name='TypeStatusCode',
        ),
        migrations.DeleteModel(
            name='TypeStatusQualityControl',
        ),
    ]
