# Generated by Django 4.0.3 on 2023-11-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gld', '0002_remove_measurementpointmetadata_censored_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterleveldossier',
            name='tube_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementpointmetadata',
            name='censored_reason',
            field=models.CharField(blank=True, choices=[('groterDanLimietwaarde', 'groterDanLimietwaarde'), ('kleinerDanLimietwaarde', 'kleinerDanLimietwaarde'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measurementpointmetadata',
            name='interpolation_code',
            field=models.CharField(blank=True, choices=[('discontinu', 'discontinu')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measurementpointmetadata',
            name='qualifier_by_category',
            field=models.CharField(blank=True, choices=[('afgekeurd', 'afgekeurd'), ('goedgekeurd', 'goedgekeurd'), ('nogNietBeoordeeld', 'nogNietBeoordeeld'), ('onbeslist', 'onbeslist'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measurementtvp',
            name='field_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='measurementtvp',
            name='measurement_point_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gld.measurementpointmetadata'),
        ),
        migrations.AddField(
            model_name='measurementtvp',
            name='measurement_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='groundwater_level_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gld.groundwaterleveldossier'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gld.observationmetadata'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gld.observationprocess'),
        ),
        migrations.AddField(
            model_name='observationmetadata',
            name='observation_type',
            field=models.CharField(blank=True, choices=[('controlemeting', 'controlemeting'), ('reguliereMeting', 'reguliereMeting')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationmetadata',
            name='responsible_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gld.responsibleparty'),
        ),
        migrations.AddField(
            model_name='observationmetadata',
            name='status',
            field=models.CharField(blank=True, choices=[('volledigBeoordeeld', 'volledigBeoordeeld'), ('voorlopig', 'voorlopig'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationprocess',
            name='air_pressure_compensation_type',
            field=models.CharField(blank=True, choices=[('capillair', 'capillair'), ('gecorrigeerdLokaleMeting', 'gecorrigeerdLokaleMeting'), ('KNMImeting', 'KNMImeting'), ('monitoringnetmeting', 'monitoringnetmeting'), ('putlocatiemeting', 'putlocatiemeting'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationprocess',
            name='evaluation_procedure',
            field=models.CharField(blank=True, choices=[('brabantWater2013', 'brabantWater2013'), ('eijkelkampDataValidatiev0.0.9', 'eijkelkampDataValidatiev0.0.9'), ('oordeelDeskundige', 'oordeelDeskundige'), ('PMBProtocolDatakwaliteitscontroleQC2018v2.0', 'PMBProtocolDatakwaliteitscontroleQC2018v2.0'), ('RWSAATGrondwaterv1.0', 'RWSAATGrondwaterv1.0'), ('validatieprocedureEvidesWaterbedrijf', 'validatieprocedureEvidesWaterbedrijf'), ('vitensBeoordelingsprotocolGrondwater', 'vitensBeoordelingsprotocolGrondwater'), ('warecoWaterDataValidatieProtocolv20200219', 'warecoWaterDataValidatieProtocolv20200219'), ('waternetBeoordelingsprocedure', 'waternetBeoordelingsprocedure'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationprocess',
            name='measurement_instrument_type',
            field=models.CharField(blank=True, choices=[('akoestischeSensor', 'akoestischeSensor'), ('akoestischHandapparaat', 'akoestischHandapparaat'), ('analoogPeilklokje', 'analoogPeilklokje'), ('druksensor', 'druksensor'), ('elektronischPeilklokje', 'elektronischPeilklokje'), ('opzetStuk', 'opzetStuk'), ('radarsensor', 'radarsensor'), ('stereoDruksensor', 'stereoDruksensor'), ('onbekend', 'onbekend'), ('onbekendPeilklokje', 'onbekendPeilklokje')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationprocess',
            name='process_reference',
            field=models.CharField(blank=True, choices=[('NEN5120v1991', 'NEN5120v1991'), ('NEN_EN_ISO22475v2006_C11v2010', 'NEN_EN_ISO22475v2006_C11v2010'), ('NEN_ISO21413v2005', 'NEN_ISO21413v2005'), ('NPR_ISO.TR23211v2009', 'NPR_ISO.TR23211v2009'), ('RWSgwmon', 'RWSgwmon'), ('STOWAgwst', 'STOWAgwst'), ('vitensMeetprotocolGrondwater', 'vitensMeetprotocolGrondwater'), ('waternetMeetprocedure', 'waternetMeetprocedure'), ('onbekend', 'onbekend')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('algoritme', 'algoritme')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gld_registration_log',
            name='quality_regime',
            field=models.CharField(blank=True, choices=[('IMBRO', 'IMBRO'), ('IMBRO/A', 'IMBRO/A')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='responsibleparty',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
