# Generated by Django 4.0.3 on 2023-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gld', '0005_measurementtvp_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtvp',
            name='calculated_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='measurementtvp',
            name='corrected_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='measurementtvp',
            name='field_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
    ]
