KADER_AANLEVERING_GMN = (
    ("waterwetStrategischGrondwaterbeheer", "waterwetStrategischGrondwaterbeheer"),
    ("waterwetGrondwaterzorgplicht", "waterwetGrondwaterzorgplicht"),
    ("waterwetOnttrekkingInfiltratie", "waterwetOnttrekkingInfiltratie"),
    ("waterwetPeilbeheer", "waterwetPeilbeheer"),
    (
        "waterwetWaterstaatswerkAanlegWijziging",
        "waterwetWaterstaatswerkAanlegWijziging",
    ),
    ("waterwetWaterstaatswerkIngreep", "waterwetWaterstaatswerkIngreep"),
    ("waterwetWaterstaatswerkBeheer", "waterwetWaterstaatswerkBeheer"),
    ("kaderrichtlijnWater", "kaderrichtlijnWater"),
    ("waterschapswet", "waterschapswet"),
    ("drinkwaterwet", "drinkwaterwet"),
    ("ontgrondingenwet", "ontgrondingenwet"),
    ("wetNatuurbescherming", "wetNatuurbescherming"),
)

MONITORINGDOEL = (
    ("strategischBeheerKwaliteitLandelijk", "strategischBeheerKwaliteitLandelijk"),
    ("strategischBeheerKwantiteitLandelijk", "strategischBeheerKwantiteitLandelijk"),
    ("strategischBeheerKwaliteitRegionaal", "strategischBeheerKwaliteitRegionaal"),
    ("strategischBeheerKwantiteitRegionaal", "strategischBeheerKwantiteitRegionaal"),
    ("beheersingStedelijkGebied", "beheersingStedelijkGebied"),
    ("gevolgenOnttrekkingKwaliteit", "gevolgenOnttrekkingKwaliteit"),
    ("gevolgenOnttrekkingKwantiteit", "gevolgenOnttrekkingKwantiteit"),
    ("gevolgenPeilbeheer", "gevolgenPeilbeheer"),
    ("gevolgenWaterstaatswerkKwaliteit", "gevolgenWaterstaatswerkKwaliteit"),
    ("gevolgenWaterstaatswerkKwantiteit", "gevolgenWaterstaatswerkKwantiteit"),
    ("waterstaatswerkBeheerKwaliteit", "waterstaatswerkBeheerKwaliteit"),
    ("waterstaatswerkBeheerKwantiteit", "waterstaatswerkBeheerKwantiteit"),
    ("veiligstellingGrondwaterKwaliteit", "veiligstellingGrondwaterKwaliteit"),
    ("veiligstellingGrondwaterKwantiteit", "veiligstellingGrondwaterKwantiteit"),
    ("waterstaatkundigeVerzorgingKwaliteit", "waterstaatkundigeVerzorgingKwaliteit"),
    ("waterstaatkundigeVerzorgingKwantiteit", "waterstaatkundigeVerzorgingKwantiteit"),
    (
        "veiligstellingDrinkwatervoorzieningKwaliteit",
        "veiligstellingDrinkwatervoorzieningKwaliteit",
    ),
    (
        "veiligstellingDrinkwatervoorzieningKwantiteit",
        "veiligstellingDrinkwatervoorzieningKwantiteit",
    ),
    ("gevolgenOntgronding", "gevolgenOntgronding"),
    ("natuurbescherming", "natuurbescherming"),
    ("natuurbeheer", "natuurbeheer"),
)
